version: "3.1"
services:
 db:
  image: postgres:12.9
  volumes: 
   - db_data:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
   POSTGRES_DB: ToonUN_Notification_ms_development
   POSTGRES_HOST_AUTH_METHOD: trust
 app:
  build: .
  volumes:
   - .:/Documentos/Universidad/Arquitectura de software/Proyecto2/ToonUN_Notification_ms
  ports:
   - "3000:3000"
  command: ./bin/rails s -p 3000 -b '0.0.0.0'
  depends_on:
   - db
  environment:
   POSTGRES_DB: ToonUN_Notification_ms_development
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 2401samu
volumes:
 db_data:
